version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule: { interval: monthly }
    groups: { docker: { patterns: ['*'] } }

  - package-ecosystem: npm
    directory: /
    schedule: { interval: monthly }
    groups: { npm: { patterns: ['*'] } }
    versioning-strategy: increase-if-necessary

  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }
    groups: { github-action: { patterns: ['*'] } }
